services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d:ro

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ecommerce_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ecommerce_redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ecommerce_rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ecommerce_minio_data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
        echo 'waiting for minio...';
        sleep 1;
      done;

      mc mb -p local/user-public || true;
      mc anonymous set download local/user-public || true;

      mc mb -p local/product-private || true;

      echo 'minio init done';
      "

volumes:
  ecommerce_postgres_data:
    name: ecommerce_postgres_data
  ecommerce_mongo_data:
    name: ecommerce_mongo_data
  ecommerce_redis_data:
    name: ecommerce_redis_data
  ecommerce_rabbitmq_data:
    name: ecommerce_rabbitmq_data
  ecommerce_minio_data:
    name: ecommerce_minio_data
